# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptAnimalOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdoptAnimalThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdoptAnimalTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status_choices', models.CharField(choices=[('Critically Endangerd', 'CE'), ('Endangered', 'E'), ('Vunerable', 'V'), ('Near Threatened', 'NT'), ('Least Concern', 'LC')], default='Critically Endangered', max_length=30)),
                ('population', models.IntegerField(blank=True, max_length=10, null=True)),
                ('habitat', models.CharField(blank=True, max_length=250, null=True)),
                ('info', models.TextField()),
                ('length', models.CharField(blank=True, max_length=250, null=True)),
                ('height', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.CharField(blank=True, max_length=250, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=250, null=True)),
                ('threats', models.TextField()),
                ('profile_img', models.ImageField(upload_to='animal_profile_img')),
                ('header_img', models.ImageField(upload_to='animal_header_img')),
            ],
        ),
        migrations.AddField(
            model_name='adoptanimaltwo',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal'),
        ),
        migrations.AddField(
            model_name='adoptanimalthree',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal'),
        ),
        migrations.AddField(
            model_name='adoptanimalone',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal'),
        ),
    ]
