# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
