# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_comments', '0003_add_submit_date_index'),
        ('animals', '0003_auto_20190327_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_comments.Comment')),
                ('up_voted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
