# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 16:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=750)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_img')),
                ('adopted', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), editable='False', size=100)),
                ('rank', models.CharField(default='Praesidio Member', editable='False', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
