# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 16:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adopted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), editable='False', null=True, size=100),
        ),
    ]
